### ISSUE TITLE
Runtime configuration error: code: 404, message: Requested entity was not found

### ISSUE THREAD

**Issue by monaw** [acquia-pso/dst-entity-generate#203]
After configuring the module @ admin/config/dst_entity_generate/settings/google_sheet_api, i see the following screen:
<img width="681" alt="Screen Shot 2023-03-01 at 11 05 50 AM" src="https://user-images.githubusercontent.com/18472048/222253471-38e68072-d3c2-4cad-83c7-d25c10783a7f.png">
and the following runtime error in Drupal's log:
```
Referrer: https://deg.ddev.site/admin/config/dst_entity_generate/settings/google_sheet_api

Error while fetching data from DST Sheet Google\Service\Exception: { "error": { "code": 404, "message": "Requested entity was not found.", "errors": [ @ "message": "Requested entity was not found.", "domain": "global", "reason": "notFound" ], "status": "NOT_FOUND" } } in /var/www/html/vendor/google/apiclient/src/Http/REST.php:134 Stack trace: #0 /var/www/html/vendor/google/apiclient/src/Http/REST.php(107): Google\Http\REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google\\Service\\...') #1 [internal function]: Google\Http\REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google\\Service\\...') #2 /var/www/html/vendor/google/apiclient/src/Task/Runner.php(187): call_user_func_array(Array, Array) #3 /var/www/html/vendor/google/apiclient/src/Http/REST.php(66): Google\Task\Runner->run() #4 /var/www/html/vendor/google/apiclient/src/Client.php(921): Google\Http\REST::execute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google\\Service\\...', Array, NULL) [...]
```
I am using a fresh install of Drupal 9.5.3.

What did i miss?

**Comment by monaw** [comment]
ok, beginner error!  i did not put the right info into the "Google Sheets ID" field; once i did that, the error went away (:
